[GeneralSettings]
LogAppStartupProgress = False
UseTableEntryHeaders = True
AllowSingleTableMode = True
InsertAutoActive = True
ShowMatrixGrid = True
FocusOnGotoShortcuts = False
ZoomLevel = 24
MaximumDiffSegments = 1000
MaximumSearchResults = 1000
CopyLimit = 40000
AnimateScroll = True
AutoAdjustDataWidth = True
StretchData = True
AllowMultipleElementsPerLine = False
IsNewVersionAvailable = False
LastUpdateCheck = 11.09.2024 22:23:56
AcknowledgeTutorials = True
Base10Length = False
SpartanMode = False
MapTutorials = '''111111111111110111111111100111111101'''
RecentFiles = ["C:\Users\tobia\Desktop\Pokemon emerald revived\Pokemon-emerald-revived\Pokemon - Emerald Version (U).gba"]

[Theme]
PrimaryColor = "#dddddd"
BackgroundColor = "#222222"
HueOffset= 0.1
AccentSaturation = 0.7
AccentValue = 0.7
HighlightBrightness = 0.6
