
[[List]]
Name = '''movementtypes'''
0 = [
   '''face_down''',
   '''face_up''',
   '''face_left''',
   '''face_right''',
   '''walk_slow_down''',
   '''walk_slow_up''',
   '''walk_slow_left''',
   '''walk_slow_right''',
   '''walk_down''',
   '''walk_up''',
   '''walk_left''',
   '''walk_right''',
   '''jump_2_down''',
   '''jump_2_up''',
   '''jump_2_left''',
   '''jump_2_right''',
   '''delay_1''',
   '''delay_2''',
   '''delay_4''',
   '''delay_8''',
   '''delay_16''',
   '''walk_fast_down''',
   '''walk_fast_up''',
   '''walk_fast_left''',
   '''walk_fast_right''',
   '''walk_in_place_slow_down''',
   '''walk_in_place_slow_up''',
   '''walk_in_place_slow_left''',
   '''walk_in_place_slow_right''',
   '''walk_in_place_down''',
   '''walk_in_place_up''',
   '''walk_in_place_left''',
   '''walk_in_place_right''',
   '''walk_in_place_fast_down''',
   '''walk_in_place_fast_up''',
   '''walk_in_place_fast_left''',
   '''walk_in_place_fast_right''',
   '''walk_in_place_fastest_down''',
   '''walk_in_place_fastest_up''',
   '''walk_in_place_fastest_left''',
   '''walk_in_place_fastest_right''',
   '''ride_water_current_down''',
   '''ride_water_current_up''',
   '''ride_water_current_left''',
   '''ride_water_current_right''',
   '''walk_fastest_down''',
   '''walk_fastest_up''',
   '''walk_fastest_left''',
   '''walk_fastest_right''',
   '''slide_down''',
   '''slide_up''',
   '''slide_left''',
   '''slide_right''',
   '''player_run_down''',
   '''player_run_up''',
   '''player_run_left''',
   '''player_run_right''',
   '''start_anim_in_direction''',
   '''jump_special_down''',
   '''jump_special_up''',
   '''jump_special_left''',
   '''jump_special_right''',
   '''face_player''',
   '''face_away_player''',
   '''lock_facing_direction''',
   '''unlock_facing_direction''',
   '''jump_down''',
   '''jump_up''',
   '''jump_left''',
   '''jump_right''',
   '''jump_in_place_down''',
   '''jump_in_place_up''',
   '''jump_in_place_left''',
   '''jump_in_place_right''',
   '''jump_in_place_down_up''',
   '''jump_in_place_up_down''',
   '''jump_in_place_left_right''',
   '''jump_in_place_right_left''',
   '''face_original_direction''',
   '''nurse_joy_bow''',
   '''enable_jump_landing_ground_effect''',
   '''disable_jump_landing_ground_effect''',
   '''disable_anim''',
   '''restore_anim''',
   '''set_invisible''',
   '''set_visible''',
   '''emote_exclamation_mark''',
   '''emote_question_mark''',
   '''emote_heart''',
   '''reveal_trainer''',
   '''rock_smash_break''',
   '''cut_tree''',
   '''set_fixed_priority''',
   '''clear_fixed_priority''',
   '''init_affine_anim''',
   '''clear_affine_anim''',
   '''hide_reflection''',
   '''show_reflection''',
   '''walk_down_start_affine''',
   '''walk_down_affine''',
]
140 = [
   '''walk_diag_northwest''',
   '''walk_diag_northeast''',
   '''walk_diag_southwest''',
   '''walk_diag_southeast''',
   '''walk_slow_diag_northwest''',
   '''walk_slow_diag_northeast''',
   '''walk_slow_diag_southwest''',
   '''walk_slow_diag_southeast''',
   '''store_lock_anim''',
   '''free_unlock_anim''',
   '''walk_left_affine''',
   '''walk_right_affine''',
   '''levitate''',
   '''stop_levitate''',
   '''destroy_extra_task''',
   '''figure_8''',
   '''fly_up''',
   '''fly_down''',
]

[[List]]
Name = '''pocketid'''
1 = [
   '''item''',
   '''ball''',
   '''tm''',
   '''berry''',
   '''key'''
]

[[List]]
Name = '''effectanimations'''
0 = [
   '''FormChange''',
   '''StatChange''',
   '''SubstituteFade''',
   '''SubstituteAppear''',
   '''PokeblockThrow''',
   '''ItemKnockOff''',
   '''TurnTrap''',
   '''HeldItemEffect''',
   '''SmokeBall''',
   '''FocusBand''',
   '''Rain''',
   '''Sun''',
   '''Sandstorm''',
   '''Hail''',
   '''LeechSeedDrain''',
   '''ConfuseHit''',
   '''ItemSteal''',
   '''SnatchMove''',
   '''FutureSight''',
   '''DoomDesire''',
   '''FocusPunchSetUp''',
   '''IngrainHeal''',
   '''WishHeal''',
]

[[List]]
Name = '''friendshipevents'''
0 = [
   '''GrowLevel''',
   '''Vitamin''',
   '''BattleItem''',
   '''LeagueBattle''',
   '''LearnTMHM''',
   '''Walking''',
   '''FaintInBattle''',
   '''FaintOutsideBattle''',
   '''FaintInBattleBigLevelGap''',
]

[[List]]
Name = '''MapAttributeBehaviors'''
0 = [
    '''Normal''',
    '''Secret_Base_Wall''',
    '''Tall_Grass''',
    '''Long_Grass''',
    '''Unused_04''',
    '''Unused_05''',
    '''Deep_Sand''',
    '''Short_Grass''',
    '''Cave''',
    '''Long_Grass_South_Edge''',
    '''No_Running''',
    '''Indoor_Encounter''',
    '''Mountain_Top''',
    '''Battle_Pyramid_Warp''',
    '''Mossdeep_Gym_Warp''',
    '''Mt_Pyre_Hole''',
    '''Pond_Water''',
    '''Semi_Deep_Water''',
    '''Deep_Water''',
    '''Waterfall''',
    '''Sootopolis_Deep_Water''',
    '''Ocean_Water''',
    '''Puddle''',
    '''Shallow_Water''',
    '''Unused_Sootopolis_Deep_Water''',
    '''No_Surfacing''',
    '''Unused_Sootopolis_Deep_Water_2''',
    '''Stairs_Outside_Abandoned_Ship''',
    '''Shoal_Cave_Entrance''',
    '''Unused_1d''',
    '''Unused_1e''',
    '''Unused_1f''',
    '''Ice''',
    '''Sand''',
    '''Seaweed''',
    '''Unused_23''',
    '''Ashgrass''',
    '''Footprints''',
    '''Thin_Ice''',
    '''Cracked_Ice''',
    '''Hot_Springs''',
    '''Lavaridge_Gym_B1f_Warp''',
    '''Seaweed_No_Surfacing''',
    '''Reflection_Under_Bridge''',
    '''Unused_2c''',
    '''Unused_2d''',
    '''Unused_2e''',
    '''Unused_2f''',
    '''Impassable_East''',
    '''Impassable_West''',
    '''Impassable_North''',
    '''Impassable_South''',
    '''Impassable_Northeast''',
    '''Impassable_Northwest''',
    '''Impassable_Southeast''',
    '''Impassable_Southwest''',
    '''Jump_East''',
    '''Jump_West''',
    '''Jump_North''',
    '''Jump_South''',
    '''Jump_Northeast''',
    '''Jump_Northwest''',
    '''Jump_Southeast''',
    '''Jump_Southwest''',
    '''Walk_East''',
    '''Walk_West''',
    '''Walk_North''',
    '''Walk_South''',
    '''Slide_East''',
    '''Slide_West''',
    '''Slide_North''',
    '''Slide_South''',
    '''Trick_House_Puzzle_8_Floor''',
    '''Unused_49''',
    '''Unused_4a''',
    '''Unused_4b''',
    '''Unused_4c''',
    '''Unused_4d''',
    '''Unused_4e''',
    '''Unused_4f''',
    '''Eastward_Current''',
    '''Westward_Current''',
    '''Northward_Current''',
    '''Southward_Current''',
    '''Unused_54''',
    '''Unused_55''',
    '''Unused_56''',
    '''Unused_57''',
    '''Unused_58''',
    '''Unused_59''',
    '''Unused_5a''',
    '''Unused_5b''',
    '''Unused_5c''',
    '''Unused_5d''',
    '''Unused_5e''',
    '''Unused_5f''',
    '''Non_Animated_Door''',
    '''Ladder''',
    '''East_Arrow_Warp''',
    '''West_Arrow_Warp''',
    '''North_Arrow_Warp''',
    '''South_Arrow_Warp''',
    '''Cracked_Floor_Hole''',
    '''Aqua_Hideout_Warp''',
    '''Lavaridge_Gym_1f_Warp''',
    '''Animated_Door''',
    '''Up_Escalator''',
    '''Down_Escalator''',
    '''Water_Door''',
    '''Water_South_Arrow_Warp''',
    '''Deep_South_Warp''',
    '''Unused_6f''',
    '''Bridge_Over_Ocean''',
    '''Bridge_Over_Pond_Low''',
    '''Bridge_Over_Pond_Med''',
    '''Bridge_Over_Pond_High''',
    '''Pacifidlog_Vertical_Log_Top''',
    '''Pacifidlog_Vertical_Log_Bottom''',
    '''Pacifidlog_Horizontal_Log_Left''',
    '''Pacifidlog_Horizontal_Log_Right''',
    '''Fortree_Bridge''',
    '''Unused_79''',
    '''Bridge_Over_Pond_Med_Edge_1''',
    '''Bridge_Over_Pond_Med_Edge_2''',
    '''Bridge_Over_Pond_High_Edge_1''',
    '''Bridge_Over_Pond_High_Edge_2''',
    '''Unused_Bridge''',
    '''Bike_Bridge_Over_Barrier''',
    '''Counter''',
    '''Unused_81''',
    '''Unused_82''',
    '''Pc''',
    '''Cable_Box_Results_1''',
    '''Region_Map''',
    '''Television''',
    '''Pokeblock_Feeder''',
    '''Unused_88''',
    '''Slot_Machine''',
    '''Roulette''',
    '''Closed_Sootopolis_Door''',
    '''Trick_House_Puzzle_Door''',
    '''Petalburg_Gym_Door''',
    '''Running_Shoes_Instruction''',
    '''Questionnaire''',
    '''Secret_Base_Spot_Red_Cave''',
    '''Secret_Base_Spot_Red_Cave_Open''',
    '''Secret_Base_Spot_Brown_Cave''',
    '''Secret_Base_Spot_Brown_Cave_Open''',
    '''Secret_Base_Spot_yellow_Cave''',
    '''Secret_Base_Spot_yellow_Cave_Open''',
    '''Secret_Base_Spot_Tree_Left''',
    '''Secret_Base_Spot_Tree_Left_Open''',
    '''Secret_Base_Spot_Shrub''',
    '''Secret_Base_Spot_Shrub_Open''',
    '''Secret_Base_Spot_Blue_Cave''',
    '''Secret_Base_Spot_Blue_Cave_Open''',
    '''Secret_Base_Spot_Tree_Right''',
    '''Secret_Base_Spot_Tree_Right_Open''',
    '''Unused_9e''',
    '''Unused_9f''',
    '''Berry_Tree_Soil''',
    '''Unused_A1''',
    '''Unused_A2''',
    '''Unused_A3''',
    '''Unused_A4''',
    '''Unused_A5''',
    '''Unused_A6''',
    '''Unused_A7''',
    '''Unused_A8''',
    '''Unused_A9''',
    '''Unused_Aa''',
    '''Unused_Ab''',
    '''Unused_Ac''',
    '''Unused_Ad''',
    '''Unused_Ae''',
    '''Unused_Af''',
    '''Secret_Base_Pc''',
    '''Secret_Base_Register_Pc''',
    '''Secret_Base_Scenery''',
    '''Secret_Base_Trainer_Spot''',
    '''Secret_Base_Decoration''',
    '''Holds_Small_Decoration''',
    '''Unused_B6''',
    '''Secret_Base_North_Wall''',
    '''Secret_Base_Balloon''',
    '''Secret_Base_Impassable''',
    '''Secret_Base_Glitter_Mat''',
    '''Secret_Base_Jump_Mat''',
    '''Secret_Base_Spin_Mat''',
    '''Secret_Base_Sound_Mat''',
    '''Secret_Base_Breakable_Door''',
    '''Secret_Base_Sand_Ornament''',
    '''Impassable_South_And_North''',
    '''Impassable_West_And_East''',
    '''Secret_Base_Hole''',
    '''Holds_Large_Decoration''',
    '''Secret_Base_Tv_Shield''',
    '''Player_Room_Pc_On''',
    '''Secret_Base_Decoration_Base''',
    '''Secret_Base_Poster''',
    '''Unused_C8''',
    '''Unused_C9''',
    '''Unused_Ca''',
    '''Unused_Cb''',
    '''Unused_Cc''',
    '''Unused_Cd''',
    '''Unused_Ce''',
    '''Unused_Cf''',
    '''Muddy_Slope''',
    '''Bumpy_Slope''',
    '''Cracked_Floor''',
    '''Isolated_Vertical_Rail''',
    '''Isolated_Horizontal_Rail''',
    '''Vertical_Rail''',
    '''Horizontal_Rail''',
    '''Unused_D7''',
    '''Unused_D8''',
    '''Unused_D9''',
    '''Unused_Da''',
    '''Unused_Db''',
    '''Unused_Dc''',
    '''Unused_Dd''',
    '''Unused_De''',
    '''Unused_Df''',
    '''Picture_Book_Shelf''',
    '''Bookshelf''',
    '''Pokemon_Center_Bookshelf''',
    '''Vase''',
    '''Trash_Can''',
    '''Shop_Shelf''',
    '''Blueprint''',
    '''Cable_Box_Results_2''',
    '''Wireless_Box_Results''',
    '''Trainer_Hill_Timer''',
    '''Sky_Pillar_Closed_Door''',
    '''Unused_Eb''',
    '''Unused_Ec''',
    '''Unused_Ed''',
    '''Unused_Ee''',
    '''Unused_Ef''',
]

[[List]]
Name = '''encountersongs'''
0 = [
   '''boy''',
   '''girl''',
   '''tubers/young couples''',
   '''suspicious''',
   '''intense''',
   '''cooltrainer''',
   '''aqua''',
   '''magma''',
   '''swimmer''',
   '''twins''',
   '''elite4''',
   '''hiker/sailor''',
   '''interviewer''',
   '''rich''',
]