
[[OffsetPointer]]
Address = 0x040898
Offset = 0x000004

[[OffsetPointer]]
Address = 0x12182C
Offset = 0x000004

[[OffsetPointer]]
Address = 0x107154
Offset = 0x000010

[[OffsetPointer]]
Address = 0x0FA8C0
Offset = -8

[[OffsetPointer]]
Address = 0x0FA8E0
Offset = -8
